version: "3.6"
services:
  telegraf:
    image: "telegraf:${TELEGRAF_VERSION}"
    container_name: "${TELEGRAF_CONTAINER_NAME}"
    restart: always
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - "${TELEGRAF_STATSD_PORT}:8125"

  influxdb:
    image: "influxdb:${INFLUXDB_VERSION}"
    container_name: "${INFLUXDB_CONTAINER_NAME}"
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "${INFLUXDB_INIT_MODE}"
      DOCKER_INFLUXDB_INIT_USERNAME: "${INFLUXDB_USERNAME}"
      DOCKER_INFLUXDB_INIT_PASSWORD: "${INFLUXDB_PASSWORD}"
      DOCKER_INFLUXDB_INIT_ORG: "${INFLUXDB_ORG}"
      DOCKER_INFLUXDB_INIT_BUCKET: "${INFLUXDB_BUCKET}"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "${INFLUXDB_ADMIN_TOKEN}"
    ports:
      - "${INFLUXDB_WEB_PORT}:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
      - influxdb_data:/var/lib/influxdb2
      - influxdb_data:/etc/influxdb2

  grafana:
    image: "grafana/grafana:${GRAFANA_VERSION}"
    container_name: "${GRAFANA_CONTAINER_NAME}"
    restart: always
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: "${GRAFANA_USERNAME}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_PASSWORD}"
    links:
      - influxdb
    ports:
      - "${GRAFANA_WEB_PORT}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana:/etc/grafana/provisioning

  traefik:
    image: "traefik:${TRAEFIK_VERSION}"
    container_name: "${TRAEFIK_CONTAINER_NAME}"
    restart: always
    volumes:
      - ./traefik:/etc/traefik/
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      - "${TRAEFIK_HTTPS_PORT}:443"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"

volumes:
  grafana_data: {}
  influxdb_data: {}
