_format_version: "2.1"
_transform: true

# services:
#   - name: auth
#     url: http://host.docker.internal:5000
#     routes:
#       - name: auth-route
#         paths:
#           - /auth

plugins:
  - name: prometheus
